source "http://rubygems.org"

def find_alternative(local_dir, git)
  unless local_dir.start_with? '/'
    local_dir = File.join(File.dirname(__FILE__), local_dir)
  end
  puts "Checking for '#{local_dir}'"
  Dir.exist?(local_dir) ? {path: local_dir} : {git: git}
end

unless Dir.exist?('../../tuhura-gems')
  git 'git://github.com/maxott/tuhura-gems.git' do
    gem 'tuhura-common'
  end
end
unless Dir.exist?('../../../omf6')
  git 'git://github.com/mytestbed/omf.git' do
    gem 'omf_common'
  end
end


# gem 'oml4r', :git => 'git://github.com/mytestbed/oml4r.git'
# gem 'thread', :git => 'git://github.com/maxott/ruby-thread.git'
# #gem 'tuhura-common', find_alternative('../tuhura-common', 'git://github.com/maxott/tuhura-gems.git')
# gem 'omf_common', find_alternative('../../../omf6/omf_common', 'git://github.com/mytestbed/omf.git')
# gem 'amqp'
# gem 'json-jwt'