source "http://rubygems.org"

def find_alternative(local_dir, git)
  unless local_dir.start_with? '/'
    local_dir = File.join(File.dirname(__FILE__), local_dir)
  end
  #puts "Checking for '#{local_dir}'"
  Dir.exist?(local_dir) ? {path: local_dir} : {git: git}
end

unless Dir.exist?('../../tuhura-gems')
  git 'git://github.com/maxott/tuhura-gems.git' do
    gem 'tuhura-common'
  end
end

gem 'tuhura-common', find_alternative('../tuhura-common', 'git://github.com/maxott/tuhura-gems.git')

# they shouldn't be here
gem 'logging'
gem 'avro'
gem 'kafka-rb'
gem 'aws-sdk'
gem 'oml4r', :git => 'git://github.com/mytestbed/oml4r.git'
gem 'active_support'
gem 'i18n'
