source "http://rubygems.org"

#gemspec
gem 'kafka-rb'
# gem 'hbase-jruby'
# gem 'log4jruby'
# gem 'zookeeper'

gem 'oml4r', :git => 'git://github.com/mytestbed/oml4r.git'
gem 'logging'
#gem 'thread', :git => 'git://github.com/maxott/ruby-thread.git'
